#!/usr/bin/env bash

# This script creates a host config file for CMake then runs CMake

# Fill in the values below based on the build
CUR_DIR=${PWD}
BUILD_DIR=$1

rm -rf $BUILD_DIR
mkdir -p $BUILD_DIR

cat > $BUILD_DIR/config.sh <<EOF
# CMake settings. Adjust the last entry per line as needed
# NOTE: Many entries try to find things by default using which.
# Remove these and add explicit paths unless you know they are
# correct
#------------------------------------------------------------
CMAKE_SETTINGS=(
    "CMAKE_INSTALL_PREFIX|PATH|install"
    "CMAKE_BUILD_TYPE|STRING|Release"
    "CMAKE_C_COMPILER|PATH|$(which gcc)"
    "CMAKE_CXX_COMPILER|PATH|$(which g++)"
    # MPI
    "ENABLE_MPI|BOOL|ON"
    "MPI_C_COMPILER|PATH|$(which mpicc)"
    "MPI_CXX_COMPILER|PATH|$(which mpicxx)"
    # Testing
    "POLYTOPE_ENABLE_TESTING|BOOL|OFF"
    # Silo
    "POLYTOPE_ENABLE_SILO|BOOL|OFF"
    "silo_DIR|PATH|/path/to/silo"
    "hdf5_DIR|PATH|/path/to/hdf5"
    # Python
    "POLYTOPE_ENABLE_PYTHON|BOOL|OFF"
    "python_DIR|PATH|/path/to/python"
    # 2D options
    "POLYTOPE_ENABLE_HIBIT2D|BOOL|OFF"
    "POLYTOPE_ENABLE_BOOST|BOOL|OFF"
    "boost_DIR|PATH|/path/to/boost"
    "POLYTOPE_ENABLE_TRIANGLE|BOOL|OFF"
    "triangle_SRC_DIR|PATH|/path/to/triangle"
    # 3D options
    "POLYTOPE_ENABLE_TETGEN|BOOL|OFF"
    "tetgen_DIR|PATH|/path/to/tetgen"
    "POLYTOPE_ENABLE_QHULL|BOOL|OFF"
    "qhull_DIR|PATH|/path/to/qhull"
)

# Copy our template config script into place.
{
    echo "# Generated file"
    for setting in "\${CMAKE_SETTINGS[@]}"; do
        IFS='|' read -r name type value <<< "\$setting"
        printf 'set(%s "%s" CACHE %s "")\n' "\$name" "\$value" "\$type"
    done
} > host-config.cmake

cmake $CUR_DIR -C host-config.cmake
EOF

# Give instructions.
echo "Your build directory $1 is ready."
echo "To configure your build:"
echo "  1. cd $1"
echo "  2. Edit the variables in config.sh as desired (enable MPI, enable Silo, etc)"
echo "  3. sh config.sh"
echo "  4. Build using 'make', 'ninja', or your selected IDE"
echo "  5. If tests are enabled, you run them in the build directory using the ctest command"
